# Generated by Django 2.2 on 2020-02-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
